name: pr

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Specify the Go version you want to use

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build